fastlane_version "2.90.0"

default_platform :ios

# Set by build environment
# FL_HOCKEY_API_TOKEN
# RZ_KEYCHAIN_PASSWORD
# SLACK_URL - set the hook URL in the CircleCI environment

ENV['RZ_ARTIFACTS'] ||= ENV['CIRCLE_ARTIFACTS'] || './build'
ENV['RZ_TEST_REPORTS'] ||= ENV['CIRCLE_TEST_REPORTS'] || './build'
ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '120'
ENV['CI_BUILD'] = 'yes'
ENV['GYM_OUTPUT_NAME'] = 'PRODUCTNAME'
ENV['FL_HOCKEY_IPA'] = "#{ENV['RZ_ARTIFACTS']}/#{ENV['GYM_OUTPUT_NAME']}.ipa"
ENV['FL_HOCKEY_NOTIFY'] = '0'

platform :ios do

  before_all do
    if ENV['RZ_ARTIFACTS'] && ENV['RZ_ARTIFACTS'].length > 0
      sh 'rm -rf $RZ_ARTIFACTS && mkdir $RZ_ARTIFACTS'
    end
    install_provisioning_profiles(override_provisioning_profiles: true)
  end

  desc "Runs tests"
  lane :test do
    scan_scheme = "debug-PRODUCTNAME"
    derived_data_path = "#{ENV['RZ_TEST_REPORTS']}/derived_data"

    scan(
      output_types: 'junit,html',
      scheme: scan_scheme,
      output_directory: "#{ENV['RZ_TEST_REPORTS']}/scan",
      buildlog_path: "#{ENV['RZ_ARTIFACTS']}",
      code_coverage: true,
      derived_data_path: derived_data_path
    )
    if !ENV['CIRCLE_TEST_REPORTS'].nil?
      # CircleCI requires the "xml" extension for test reporting
      puts "Fixing JUnit report name"
      sh "cp #{ENV['RZ_TEST_REPORTS']}/scan/report.junit #{ENV['RZ_TEST_REPORTS']}/scan/report.xml"
    end

    slather_use_coveralls = "false"
    slather_use_circleci = "false"

    if !ENV['CIRCLE_BUILD_NUM'].nil?
      slather_use_circleci = "true"
    end

    xcov_scheme = scan_scheme
    xcov_workspace = "PRODUCTNAME.xcworkspace"

    xcov(
      workspace: xcov_workspace,
      scheme: xcov_scheme,
      output_directory: "#{ENV['RZ_TEST_REPORTS']}/xcov",
      # Add targets here as you create internal frameworks
      include_targets: "debug-PRODUCTNAME.app, Services.framework",
      derived_data_path: derived_data_path
    )

    slather_proj = "PRODUCTNAME.xcodeproj"
    slather_workspace = xcov_workspace
    # Only the Services scheme seems to work. It cannot find our app target schemes. 
    slather_scheme = "Services"
    slather_output_directory = "#{ENV['RZ_TEST_REPORTS']}/slather"

    # html and cobertura_xml output must be run separately
    slather(
      proj: slather_proj,
      workspace: slather_workspace,
      scheme: slather_scheme,
      output_directory: slather_output_directory,
      html: "true",
      build_directory: derived_data_path
    )
    # Using Cobertura XML allows us to upload to Codecov.io
    # Uploading to codecov is handled separately in the .circleci/config.yml
    slather(
      proj: slather_proj,
      workspace: slather_workspace,
      scheme: slather_scheme,
      output_directory: slather_output_directory,
      circleci: slather_use_circleci,
      coveralls: slather_use_coveralls,
      cobertura_xml: "true",
      build_directory: derived_data_path
    )

  end

  desc "Builds and submits a Develop release to Hockey"
  lane :develop do
    build("develop-PRODUCTNAME", 'enterprise', {
      teamID: "XRTVVR644Y",
      signingCertificate: "iPhone Distribution",
      provisioningProfiles: { "com.raizlabs.PRODUCTNAME.develop" => "Raizlabs Generic Enterprise Profile" }
    })    
    hockey(public_identifier: 'ZZHOCKEY_DEVELOP_IDZZ')
    # upload_symbols_to_crashlytics(:api_token => 'ZZCRASHLYTICS_API_TOKEN_DEVELOPZZ')
    slack(message: "Successfully uploaded build #{build_number} to develop", success: true)
  end

  desc "Builds and submits a Sprint release to Hockey"
  lane :sprint do
    build("sprint-PRODUCTNAME", 'enterprise', {
      teamID: "XRTVVR644Y",
      signingCertificate: "iPhone Distribution",
      provisioningProfiles: { "com.raizlabs.PRODUCTNAME.sprint" => "Raizlabs Generic Enterprise Profile" }
    })  
    hockey(public_identifier: 'ZZHOCKEY_SPRINT_IDZZ')
    # upload_symbols_to_crashlytics(:api_token => 'ZZCRASHLYTICS_API_TOKEN_SPRINTZZ')
    slack(message: "Successfully uploaded build #{build_number} to sprint", success: true)
  end

  # desc "Builds and submits an App Store release to TestFlight"
  lane :beta do
  #  build("appStore-PRODUCTNAME", 'app-store', {
  #    teamID: "",
  #    signingCertificate: "iPhone Distribution",
  #    provisioningProfiles: { "" => "" }
  #  })    
  #  pilot(
  #   distribute_external: false,
  #     skip_waiting_for_build_processing: true,
  #  )
  #  upload_symbols_to_crashlytics(:api_token => 'ZZCRASHLYTICS_API_TOKEN_APPSTOREZZ')
  #  slack(message: "Successfully uploaded build #{build_number} to test flight", success: true)
  end

  # Helpers ----------------------

  desc "Sync Project and Directory Structure"
  lane :synx do
    sh "cd .. && synx PRODUCTNAME.xcodeproj"
  end

  def build(scheme, export_method, export_options)
    unlock_keychain(path: './Signing/Raizlabs-PRODUCTNAME.keychain', password: ENV['RZ_KEYCHAIN_PASSWORD'] )
    gym(
      output_directory: "#{ENV['RZ_ARTIFACTS']}",
      output_name: "PRODUCTNAME",
      export_method: export_method,
      scheme: scheme,
      include_bitcode: true,
      xcargs: "BUILD_NUMBER=#{build_number}",
      buildlog_path: "#{ENV['RZ_ARTIFACTS']}",
      export_options: export_options
    )
  end

  def build_number
    `git rev-list HEAD --count`.chomp()
  end

end
