platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target '{{ cookiecutter.project_name | replace(' ', '') }}' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'Marshal'
  pod 'SwiftLint'

  pod 'BonMot'
  pod 'Anchorage'
  pod 'Swiftilities'

  pod 'GoogleAnalytics',   '~>3.0'

  target '{{ cookiecutter.project_name | replace(' ', '') }}Tests' do
    pod 'OHHTTPStubs/Swift'
  end

end


pod 'SwiftGen'

# This is a hack to support both 3.2 and 4.0 pods. Add the pod name to the array below to build in 4.0.
#
# https://github.com/CocoaPods/CocoaPods/issues/7134 is the official thread tracking the issue.
SWIFT_4_PODS=[]

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-{{ cookiecutter.project_name | replace(' ', '') }}/Pods-{{ cookiecutter.project_name | replace(' ', '') }}-acknowledgements.plist', '{{ cookiecutter.project_name | replace(' ', '') }}/Resources/Acknowledgements.plist', :remove_destination => true)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = SWIFT_4_PODS.include?(target.name) ? '4.0' : '3.2'
    end
  end
end

