platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared
    pod 'Marshal'
    pod 'KeychainAccess'
    pod 'BonMot'
    pod 'Alamofire'
    pod 'Anchorage'
    pod 'Swiftilities', :git => 'https://github.com/Raizlabs/Swiftilities', :branch => 'feature/heyltsjay/swift4_2'
end

target '{{ cookiecutter.project_name | replace(' ', '') }}' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'GoogleAnalytics',   '~>3.0'
  
  pod 'SimulatorStatusMagic', :configurations => ['Debug']

  target '{{ cookiecutter.project_name | replace(' ', '') }}Tests' do
    pod 'OHHTTPStubs/Swift'
  end

  shared()
end

target 'Services' do
    shared()
end

pod 'SwiftGen'
pod 'Sourcery', '~> 0.15.0'
pod 'SwiftLint'
