# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPad Pro (9.7-inch)",
  # "iPad Pro (12.9-inch)",
  # "iPad Pro (10.5-inch)", # My not be supported in iTunes Connect, so do a test upload
])

# The name of the scheme which contains the UI Tests
scheme("Screenshots")

# these will be generated on run, so no need to keep old ones.
clear_previous_screenshots(true)

# cut your losses
stop_after_first_error(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# prevent rebuilds every time you run snapshot by putting derived data
# in a deterministic place
derived_data_path("build/snapshot_derived_data")

# For more information about all available options run
# fastlane action snapshot
