source 'https://rubygems.org'

gem 'fastlane', '~> 2.85.0'
gem 'cocoapods', '~> 1.4.0'
gem 'synx', '~> 0.2.1'
gem 'nanaimo', '~> 0.2.2'

plugins_path = File.join(File.dirname(__FILE__), 'app', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)