platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def shared
    pod 'Marshal'
    pod 'KeychainAccess'
    pod 'BonMot'
    pod 'Alamofire'
    pod 'Anchorage'
    pod 'Swiftilities'
end

target 'PRODUCTNAME' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'GoogleAnalytics',   '~>3.0'

  target 'PRODUCTNAMETests' do
    pod 'OHHTTPStubs/Swift'
  end

  shared()
end

target 'Services' do
    shared()
end


pod 'SwiftGen'
pod 'Sourcery'
pod 'SwiftLint'

# This is a hack to support both 3.2 and 4.0 pods. Add the pod name to the array below to build in 4.0.
#
# https://github.com/CocoaPods/CocoaPods/issues/7134 is the official thread tracking the issue.
SWIFT_4_PODS=[]

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-PRODUCTNAME/Pods-PRODUCTNAME-acknowledgements.plist', 'PRODUCTNAME/Resources/Acknowledgements.plist', :remove_destination => true)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = SWIFT_4_PODS.include?(target.name) ? '4.0' : '3.2'
    end
  end
end

