platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'PRODUCTNAME' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'Marshal'

  pod 'BonMot'
  pod 'Anchorage'
  pod 'Swiftilities'

  pod 'GoogleAnalytics',   '~>3.0'

  target 'PRODUCTNAMETests' do
    pod 'OHHTTPStubs/Swift'
  end

end


pod 'SwiftGen'

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-PRODUCTNAME/Pods-PRODUCTNAME-acknowledgements.plist', 'PRODUCTNAME/Resources/Acknowledgements.plist', :remove_destination => true)
end

